//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSharp.SqlCeImpl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeoSharpSQLCEEntities : DbContext
    {
        public GeoSharpSQLCEEntities()
            : base("name=GeoSharpSQLCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ISO3166_2_156> ISO3166_2_156 { get; set; }
        public virtual DbSet<ISO3166> ISO3166Set { get; set; }
        public virtual DbSet<ISO3166_1_ALPHA_2> ISO3166_1_ALPHA_2 { get; set; }
        public virtual DbSet<ISO3166_1_ALPHA_3> ISO3166_1_ALPHA_3 { get; set; }
        public virtual DbSet<ISO3166_1_NUMERIC> ISO3166_1_NUMERIC { get; set; }
        public virtual DbSet<ISO3166_2> ISO3166_2 { get; set; }
        public virtual DbSet<ISO3166_3> ISO3166_3 { get; set; }
    }
}
