//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSharp.SqlCeImpl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISO3166_1_ALPHA_2
    {
        public string Code { get; set; }
        public string CountryName { get; set; }
        public short Year { get; set; }
        public string ccTLD { get; set; }
        public string ISO3166_2 { get; set; }
        public string Notes { get; set; }
    }
}
