//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSharp.SqlCeImpl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISO3166_3
    {
        public int FormerCountryName { get; set; }
        public string FormerCodes { get; set; }
        public string PeriodOfValidity { get; set; }
        public string ISO3166_3Code { get; set; }
        public string NewCountryName { get; set; }
        public string NewCountryCode { get; set; }
    }
}
