//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoSharp.SqlCeImpl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISO3166_1_ALPHA_3
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CountryName { get; set; }
    }
}
